name: Test
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 24.x
      uses: actions/setup-node@v5
      with:
        node-version: 24.x
    - name: npm install
      run: npm install
    - name: npm lint
      run: npm run lint
  test:
    uses: pkgjs/action/.github/workflows/node-test.yaml@v0
